//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductInventoryMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Customers()
        {
            this.Tbl_Sales = new HashSet<Tbl_Sales>();
        }
    
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Please write Customer name")]
        [StringLength(50, ErrorMessage ="Max character can be 50")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Please write Customer surname")]
        [StringLength(50, ErrorMessage = "Max character can be 50")]
        public string CustomerSurname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sales> Tbl_Sales { get; set; }
    }
}
