//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductInventoryMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int SaleID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<byte> Piece { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
    }
}
